import Link from "next/link";
import { ArrowRight, CarFront, MapPin, Star, ImageOff } from "lucide-react";
import type { ParkingSearchResult } from "@/types/parking";
import { Badge } from "@/components/ui/Badge";
import { FallbackImage } from "@/components/ui/FallbackImage";
import { mallForParkingName } from "@/data/parkkarData";

export function ParkingCard({ spot }: { spot: ParkingSearchResult }) {
 const mall=mallForParkingName(spot.name);
 const placeholder=<div className="absolute inset-0 bg-[radial-gradient(circle_at_25%_20%,rgba(34,211,238,.30),transparent_38%),radial-gradient(circle_at_80%_70%,rgba(99,102,241,.28),transparent_45%)]"/>;
 return <article className="group overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="relative h-48 overflow-hidden bg-slate-950">{mall?.imageUrl?<FallbackImage src={mall.imageUrl} alt={`${mall.name} exterior`} className="h-full w-full object-cover opacity-75 transition duration-500 group-hover:scale-105" fallback={placeholder}/>:placeholder}<div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent to-slate-950/20"/><div className="absolute left-5 top-5"><Badge tone="info">{spot.property_type.replaceAll("_"," ")}</Badge></div><div className="absolute bottom-5 left-5 flex h-12 w-12 items-center justify-center rounded-2xl border border-white/10 bg-white/10 text-white backdrop-blur">{mall?.imageUrl?<CarFront className="h-6 w-6"/>:<ImageOff className="h-5 w-5 text-slate-400"/>}</div><div className="absolute bottom-5 right-5 rounded-2xl bg-white px-4 py-2.5 text-right"><div className="text-lg font-bold text-slate-950">{spot.min_price_per_hour ? `₹${spot.min_price_per_hour}` : "—"}</div><div className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-500">/ hour</div></div></div><div className="p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><h3 className="text-lg font-bold tracking-tight text-slate-950">{spot.name}</h3><span className="inline-flex shrink-0 items-center gap-1 rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700"><Star className="h-3.5 w-3.5 fill-current"/>{spot.avg_rating || "New"}</span></div><div className="mt-3 flex items-start gap-2 text-sm text-slate-500"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-cyan-500"/>{spot.address}, {spot.city}</div>{mall&&<p className="mt-3 text-xs font-medium text-cyan-700">{mall.mapAvailable?"Building-aware map available":"Detailed floor map unavailable"}</p>}<div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-xs"><span className="text-slate-500">{spot.review_count} {spot.review_count===1?"review":"reviews"}</span><span className="font-semibold text-emerald-600">{spot.status==="ACTIVE"?"Open for booking":"Unavailable"}</span></div><Link href={`/parking/${spot.id}`} className="mt-5 flex items-center justify-center gap-2 rounded-2xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white transition hover:-translate-y-0.5 hover:bg-slate-800">View parking <ArrowRight className="h-4 w-4"/></Link></div></article>;
}
