"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ArrowRight, CarFront, CheckCircle2, MapPin, Search, ShieldCheck, Sparkles, Wrench, Zap } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { ParkingCard } from "@/components/parking/ParkingCard";
import { ParkingDiscoveryMap } from "@/components/parking/ParkingDiscoveryMap";
import { useParking } from "@/hooks/useResources";
import { Skeleton } from "@/components/ui/Skeleton";
import { useLanguage } from "@/contexts/LanguageContext";
import { CITY_COORDS, INDIAN_CAPITALS } from "@/data/parkkarData";

export default function Home(){
 const router=useRouter(); const {t}=useLanguage(); const [city,setCity]=useState(""); const {data,isLoading}=useParking({city:city||undefined,limit:6});
 const locations=data?.data||[]; const center=CITY_COORDS[city]||CITY_COORDS.Kanpur;
 return <AppShell><main>
  <section className="relative overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(34,211,238,.15),transparent_32%),radial-gradient(circle_at_85%_35%,rgba(99,102,241,.13),transparent_35%)]"/><div className="relative mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24">
   <div className="flex flex-col justify-center"><div className="inline-flex w-fit items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-semibold text-slate-300"><Sparkles className="h-3.5 w-3.5 text-cyan-400"/>Smart parking, without the hassle</div><h1 className="mt-7 max-w-3xl text-5xl font-bold tracking-[-.05em] sm:text-6xl lg:text-7xl">{t.heroTitle}<span className="block text-cyan-400">{t.heroAccent}</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-400 sm:text-lg">{t.heroBody}</p>
   <form onSubmit={e=>{e.preventDefault();router.push(`/parking${city?`?city=${encodeURIComponent(city)}`:""}`)}} className="mt-8 rounded-3xl border border-white/10 bg-white/5 p-3"><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><label className="rounded-2xl bg-white/10 px-4 py-3"><span className="block text-[10px] font-bold uppercase tracking-[.2em] text-slate-500">{t.location}</span><span className="mt-1 flex items-center gap-2"><MapPin className="h-4 w-4 text-cyan-400"/><input list="parkkar-cities" value={city} onChange={e=>setCity(e.target.value)} placeholder="Kanpur, Lucknow, Bengaluru..." className="w-full bg-transparent text-sm outline-none placeholder:text-slate-500"/></span><datalist id="parkkar-cities">{INDIAN_CAPITALS.map(c=><option key={c} value={c}/>)}<option value="Kanpur"/></datalist></label><button className="inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-6 py-4 font-bold text-slate-950 hover:-translate-y-0.5"><Search className="h-4 w-4"/>{t.search}</button></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 px-1 text-xs text-slate-500"><span className="inline-flex items-center gap-2"><ShieldCheck className="h-3.5 w-3.5 text-cyan-400"/>Secure booking</span><span className="inline-flex items-center gap-2"><Zap className="h-3.5 w-3.5 text-amber-400"/>Live availability when integrated</span><span className="inline-flex items-center gap-2"><Wrench className="h-3.5 w-3.5 text-emerald-400"/>Vehicle care</span></div></form></div>
   <div className="hidden items-center lg:flex"><div className="w-full rounded-[34px] border border-white/10 bg-white/5 p-4"><div className="rounded-[28px] border border-white/10 bg-slate-900 p-5"><div className="flex items-center justify-between"><div><p className="font-bold">One booking. One journey.</p><p className="mt-1 text-xs text-slate-500">Parking + payment + vehicle care</p></div><span className="rounded-full bg-cyan-400/10 px-3 py-1 text-[10px] font-bold text-cyan-300">PARKKAR</span></div><div className="mt-5 grid grid-cols-3 gap-3">{[[MapPin,"Find","Nearby spaces"],[CarFront,"Book","Pick slot"],[Wrench,"Care","Clean or assist"]].map(([Icon,title,desc])=>{const I=Icon as typeof CarFront;return <div key={title as string} className="rounded-2xl border border-white/10 bg-white/5 p-4"><I className="h-5 w-5 text-cyan-400"/><p className="mt-5 font-bold">{title as string}</p><p className="mt-1 text-xs leading-5 text-slate-500">{desc as string}</p></div>})}</div></div></div></div>
  </div></section>
  <section className="bg-white px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-5"><div><div className="text-xs font-bold uppercase tracking-[.22em] text-cyan-600">NEARBY SPACES</div><h2 className="mt-2 text-3xl font-bold tracking-tight">{t.nearby}</h2><p className="mt-2 text-sm text-slate-500">Tap a card or a map marker to continue.</p></div><Link href="/parking" className="hidden text-sm font-bold text-cyan-700 sm:inline-flex">{t.explore}<ArrowRight className="ml-1 h-4 w-4"/></Link></div>
   <div className="mt-8 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="grid gap-4 sm:grid-cols-2">{isLoading?Array.from({length:4}).map((_,i)=><Skeleton key={i} className="h-[330px] rounded-3xl"/>):locations.slice(0,4).map(s=><ParkingCard key={s.id} spot={s}/>)}</div><div className="min-h-[420px]"><ParkingDiscoveryMap locations={locations} center={center} onSelect={id=>router.push(`/parking/${id}`)}/></div></div></div></section>
  <section id="how" className="bg-slate-950 px-4 py-16 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="text-xs font-bold uppercase tracking-[.22em] text-cyan-400">HOW IT WORKS</div><h2 className="mt-2 text-4xl font-bold">From search to parked.</h2><div className="mt-8 grid gap-4 md:grid-cols-4">{[["01","Search","Find parking near your destination."],["02","Choose","Pick timing, vehicle and slot."],["03","Care","Add cleaning or tyre help if needed."],["04","Park","Show your booking and follow the slot." ]].map(([n,title,text])=><div key={n} className="rounded-3xl border border-white/10 bg-white/5 p-6"><span className="text-xs font-bold text-cyan-400">{n}</span><h3 className="mt-5 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></div>)}</div></div></section>
  <section className="bg-white px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl rounded-3xl border border-slate-200 bg-slate-50 p-7 sm:p-10"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><div className="text-xs font-bold uppercase tracking-[.22em] text-cyan-600">PARKKAR CARE</div><h2 className="mt-2 text-3xl font-bold">Cleaning is a core part of the booking.</h2><p className="mt-2 max-w-2xl text-slate-500">Normal wash, interior cleaning, complete cleaning and emergency tubeless puncture assistance can be selected with parking.</p></div><Link href="/care" className="inline-flex w-fit items-center gap-2 rounded-2xl bg-slate-950 px-5 py-3 font-semibold text-white">Explore care <ArrowRight className="h-4 w-4"/></Link></div></div></section>
 </main></AppShell>
}
