"use client";
import type { ReactNode } from "react";
import Link from "next/link";
import { ArrowRight, CarFront, Heart, LogOut, Receipt, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { ProtectedRoute } from "@/components/layout/ProtectedRoute";
import { useAuth } from "@/contexts/AuthContext";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";

export default function ProfilePage(){return <ProtectedRoute><AppShell><Profile/></AppShell></ProtectedRoute>}
function Profile(){const {user,logout}=useAuth();if(!user)return null;return <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><div className="grid gap-6 lg:grid-cols-[1fr_340px]"><Card className="p-7 sm:p-9"><div className="flex items-center gap-5"><div className="flex h-16 w-16 items-center justify-center rounded-3xl bg-slate-950 text-2xl font-bold text-white">{user.name.slice(0,1).toUpperCase()}</div><div><div className="flex items-center gap-2"><h1 className="text-3xl font-bold">{user.name}</h1><Badge tone="info">{user.role}</Badge></div><p className="mt-1 text-sm text-slate-500">{user.email}</p></div></div><div className="mt-8 grid gap-3 sm:grid-cols-2"><Info label="Phone" value={user.phone}/><Info label="Account" value={user.account_status}/><Info label="Member since" value={new Date(user.created_at).toLocaleDateString("en-IN")}/><Info label="Partner commission" value={user.commission_rate_percent?`${user.commission_rate_percent}%`:"Not applicable"}/></div><div className="mt-8 flex flex-wrap gap-3"><Button variant="dark" onClick={logout}><LogOut className="h-4 w-4"/>Log out</Button></div></Card><div className="space-y-4"><Quick href="/bookings" icon={<Receipt/>} label="Bookings"/><Quick href="/vehicles" icon={<CarFront/>} label="Vehicles"/><Quick href="/favorites" icon={<Heart/>} label="Favorites"/><div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 text-emerald-600"/><div><div className="font-semibold text-emerald-900">Secure session</div><p className="mt-1 text-sm leading-6 text-emerald-700">Parkkar uses the existing authenticated API flow and clears stale sessions on unauthorized responses.</p></div></div></div></div></div></main>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-bold uppercase tracking-[0.12em] text-slate-400">{label}</div><div className="mt-1 text-sm font-semibold">{value}</div></div>}
function Quick({href,icon,label}:{href:string;icon:ReactNode;label:string}){return <Link href={href} className="flex items-center justify-between rounded-3xl border border-slate-200 bg-white p-5 shadow-sm hover:shadow-md"><div className="flex items-center gap-3"><span className="text-cyan-600">{icon}</span><span className="font-bold">{label}</span></div><ArrowRight className="h-4 w-4 text-slate-400"/></Link>}
