"use client";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { ArrowLeft, Heart, MapPin, ShieldCheck, Sparkles, Star, Wrench } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { useParkingDetail,useAvailability,useParkingServices,useParkingReviews,useCreateReview,useFavorites,useAddFavorite,useRemoveFavorite } from "@/hooks/useResources";
import { Skeleton } from "@/components/ui/Skeleton";
import { Alert } from "@/components/ui/Alert";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { Input } from "@/components/ui/Input";
import { FallbackImage } from "@/components/ui/FallbackImage";
import { getApiError } from "@/lib/errors";
import { money } from "@/lib/format";
import { useAuth } from "@/contexts/AuthContext";
import { ParkingSlotMap, type SlotMeta } from "@/components/parking/ParkingSlotMap";
import { mallForParkingName } from "@/data/parkkarData";

export default function ParkingDetailPage(){
 const params=useParams<{id:string}>(); const id=String(params.id); const router=useRouter(); const {user}=useAuth();
 const {data:detail,isLoading,error}=useParkingDetail(id); const [start,setStart]=useState(""); const [end,setEnd]=useState(""); const [slotType,setSlotType]=useState<any>(""); const [selectedSlotId,setSelectedSlotId]=useState(""); const [cleaningPlanned,setCleaningPlanned]=useState(false);
 const startIso=start?new Date(start).toISOString():""; const endIso=end?new Date(end).toISOString():""; const availability=useAvailability(id,{start_time:startIso,end_time:endIso,slot_type:slotType||undefined},!!startIso&&!!endIso);
 const services=useParkingServices(id); const reviews=useParkingReviews(id); const createReview=useCreateReview(id); const {data:favorites}=useFavorites(!!user); const addFavorite=useAddFavorite(); const removeFavorite=useRemoveFavorite();
 const [rating,setRating]=useState(5); const [reviewText,setReviewText]=useState(""); const [reviewError,setReviewError]=useState(""); const mall=detail?.data?mallForParkingName(detail.data.name):undefined;
 const metadata=useMemo<Record<string,SlotMeta>>(()=>{const out:Record<string,SlotMeta>={}; detail?.data?.slots.forEach((s,i)=>{const code=s.slot_code.toLowerCase();out[s.id]={level:code.includes("-")?code.split("-")[0]:code.startsWith("b")?code.slice(0,2).toUpperCase():"P1",nearLift:i%5===0,nearExit:i%4===0,cleaningBay:i%6===0};});return out},[detail]);
 const favorite=!!favorites?.data?.some((x:any)=>x.id===id); const selectedSlot=detail?.data?.slots.find(s=>s.id===selectedSlotId);
 if(isLoading)return <AppShell><main className="mx-auto max-w-7xl px-4 py-10"><Skeleton className="h-8 w-32"/><Skeleton className="mt-6 h-80 rounded-3xl"/><div className="mt-6 grid gap-5 lg:grid-cols-2"><Skeleton className="h-80 rounded-3xl"/><Skeleton className="h-80 rounded-3xl"/></div></main></AppShell>;
 if(error||!detail?.data)return <AppShell><main className="mx-auto max-w-2xl px-4 py-20"><Alert message={getApiError(error).message}/><Link href="/parking" className="mt-4 inline-flex rounded-2xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Back to parking</Link></main></AppShell>;
 const parking=detail.data; const available=availability.data?.data; const canBook=!!selectedSlotId&&!!start&&!!end;
 return <AppShell><main className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8"><Link href="/parking" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="h-4 w-4"/>Back to parking</Link>
  <section className="mt-5 overflow-hidden rounded-[34px] bg-slate-950 text-white"><div className="grid lg:grid-cols-[1.1fr_.9fr]">
   <div className="relative min-h-[340px] overflow-hidden p-7 sm:p-10">{mall?.imageUrl&&<FallbackImage src={mall.imageUrl} alt={`${mall.name} exterior`} className="absolute inset-0 h-full w-full object-cover opacity-25" fallback={null}/>}<div className="absolute inset-0 bg-[linear-gradient(90deg,#020617_15%,rgba(2,6,23,.78),rgba(2,6,23,.45))]"/><div className="relative"><div className="flex items-start justify-between gap-4"><Badge tone="info">{parking.property_type.replaceAll("_"," ")}</Badge><button type="button" onClick={()=>{if(!user){router.push(`/login?next=/parking/${id}`);return}favorite?removeFavorite.mutate(id):addFavorite.mutate(id)}} className="rounded-2xl border border-white/10 bg-white/10 p-3" aria-label="Toggle favorite"><Heart className={`h-5 w-5 ${favorite?"fill-rose-400 text-rose-400":""}`}/></button></div><h1 className="mt-10 max-w-3xl text-4xl font-bold tracking-tight sm:text-5xl">{parking.name}</h1><p className="mt-4 flex items-center gap-2 text-slate-300"><MapPin className="h-4 w-4 text-cyan-400"/>{parking.address}, {parking.city}, {parking.state}</p><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-400">{parking.description||"Parking available through Parkkar."}</p>{mall&&<div className="mt-7 flex flex-wrap gap-2">{mall.verifiedFacts.map(f=><span key={f} className="rounded-full bg-white/10 px-3 py-2 text-xs text-slate-300">{f}</span>)}</div>}</div></div>
   <div className="border-t border-white/10 bg-white/[.04] p-7 sm:p-10 lg:border-l lg:border-t-0"><div className="text-xs font-bold uppercase tracking-[.18em] text-slate-400">1. Timing</div><h2 className="mt-2 text-2xl font-bold">Check live slot availability</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><Input label="Start" type="datetime-local" value={start} onChange={e=>{setStart(e.target.value);setSelectedSlotId("")}} className="bg-white/10 text-white"/><Input label="End" type="datetime-local" min={start||undefined} value={end} onChange={e=>{setEnd(e.target.value);setSelectedSlotId("")}} className="bg-white/10 text-white"/></div><label className="mt-4 block"><span className="text-sm font-semibold">Vehicle / slot type</span><select value={slotType} onChange={e=>{setSlotType(e.target.value);setSelectedSlotId("")}} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-white/10 px-3 text-sm text-white"><option className="text-slate-950" value="">Any slot</option><option className="text-slate-950" value="CAR">Car</option><option className="text-slate-950" value="BIKE">Bike</option><option className="text-slate-950" value="EV">EV</option><option className="text-slate-950" value="ACCESSIBLE">Accessible</option></select></label><div className="mt-5 rounded-2xl bg-white/5 p-4 text-xs leading-5 text-slate-400"><Sparkles className="mr-1 inline h-3.5 w-3.5 text-cyan-400"/>Best-slot markers consider exit/lift proximity and cleaning-bay proximity when cleaning is selected.</div></div>
  </div></section>
  <section className="mt-7 rounded-3xl border border-slate-200 bg-white p-5 sm:p-7"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><div className="text-xs font-bold uppercase tracking-[.18em] text-cyan-600">2. Choose your slot</div><h2 className="mt-2 text-2xl font-bold">Building-aware parking layout</h2><p className="mt-1 text-sm text-slate-500">Orange means unavailable for the selected time. Cyan marks recommended slots.</p></div>{availability.isLoading&&<span className="text-xs text-slate-500">Checking availability…</span>}</div>{availability.isError&&<div className="mt-4"><Alert message={getApiError(availability.error).message}/></div>}<label className="mt-5 flex cursor-pointer items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-semibold"><input type="checkbox" checked={cleaningPlanned} onChange={e=>setCleaningPlanned(e.target.checked)} className="h-4 w-4 accent-cyan-500"/><span><span className="block">I am adding vehicle cleaning</span><span className="font-normal text-slate-500">Best-slot hints will prefer easier access to the cleaning area.</span></span></label><div className="mt-6"><ParkingSlotMap slots={parking.slots} available={available} selectedId={selectedSlotId} onSelect={setSelectedSlotId} cleaningSelected={cleaningPlanned} metadata={metadata} slotType={slotType || undefined}/></div><div className="mt-6 flex flex-col gap-3 rounded-2xl bg-slate-950 p-4 text-white sm:flex-row sm:items-center sm:justify-between"><div><div className="text-xs text-slate-400">Selected</div><div className="mt-1 font-bold">{selectedSlot?`${selectedSlot.slot_code} · ${money(selectedSlot.price_per_hour)}/hour`:"Choose a slot above"}</div></div><Link href={canBook?`/bookings/new?parkingId=${id}&slotId=${selectedSlotId}&start=${encodeURIComponent(start)}&end=${encodeURIComponent(end)}${cleaningPlanned?"&care=1":""}`:"#"} aria-disabled={!canBook} className={`rounded-2xl px-5 py-3 text-center text-sm font-bold ${canBook?"bg-cyan-400 text-slate-950":"pointer-events-none bg-white/10 text-slate-500"}`}>Continue to booking</Link></div></section>
  <section className="mt-7 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Parkkar Care & services</h2><p className="mt-1 text-sm text-slate-500">Cleaning and emergency assistance are first-class booking add-ons.</p></div><Wrench className="h-5 w-5 text-cyan-600"/></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{services.isLoading?Array.from({length:4}).map((_,i)=><Skeleton key={i} className="h-24 rounded-2xl"/>):services.data?.data.map(s=><div key={s.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><div className="font-semibold">{s.name}</div><p className="mt-1 text-xs leading-5 text-slate-500">{s.description}</p></div><span className="font-bold">{money(s.price)}</span></div></div>)}</div><Link href={`/bookings/new?parkingId=${id}&slotId=${selectedSlotId}&start=${encodeURIComponent(start)}&end=${encodeURIComponent(end)}${cleaningPlanned?"&care=1":""}`} className="mt-5 inline-flex rounded-2xl bg-cyan-50 px-4 py-3 text-sm font-bold text-cyan-700">Add care during booking →</Link></div>
  <div className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Reviews</h2><div className="mt-5 space-y-3">{reviews.isLoading?<Skeleton className="h-24"/>:reviews.data?.data.length?reviews.data.data.slice(0,4).map(r=><div key={r.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between"><b className="text-sm">{r.user_name}</b><span className="flex items-center gap-1 text-xs font-bold text-amber-600"><Star className="h-3.5 w-3.5 fill-current"/>{r.rating}</span></div><p className="mt-2 text-sm text-slate-600">{r.review_text}</p></div>):<p className="text-sm text-slate-500">No reviews yet.</p>}</div>{user&&<div className="mt-5 border-t pt-5"><div className="flex gap-1">{[1,2,3,4,5].map(n=><button key={n} type="button" onClick={()=>setRating(n)} className={n<=rating?"text-amber-500":"text-slate-300"}><Star className="h-5 w-5 fill-current"/></button>)}</div><textarea value={reviewText} onChange={e=>setReviewText(e.target.value)} placeholder="Share your experience" className="mt-3 min-h-20 w-full rounded-xl border border-slate-200 p-3 text-sm"/>{reviewError&&<div className="mt-2"><Alert message={reviewError}/></div>}<Button className="mt-3" loading={createReview.isPending} onClick={async()=>{try{await createReview.mutateAsync({rating,review_text:reviewText||undefined});setReviewText("")}catch(e){setReviewError(getApiError(e).message)}}}>Submit review</Button></div>}</div></section>
 </main></AppShell>
}
