"use client";
import Link from "next/link";
import { useRouter,useSearchParams } from "next/navigation";
import { useEffect,useMemo,useState } from "react";
import { ArrowLeft, CarFront, Clock3, Sparkles, Wrench } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { ProtectedRoute } from "@/components/layout/ProtectedRoute";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Alert } from "@/components/ui/Alert";
import { Input } from "@/components/ui/Input";
import { useCreateBooking,useParkingDetail,useVehicles,useParkingServices } from "@/hooks/useResources";
import { getApiError } from "@/lib/errors";
import { money } from "@/lib/format";
import { CareServicePicker, isVisibleForVehicle } from "@/components/care/CareServicePicker";
import type { VehicleType } from "@/types/vehicle";

export default function NewBookingPage(){return <ProtectedRoute><BookingForm/></ProtectedRoute>}
function BookingForm(){
 const query=useSearchParams(); const router=useRouter(); const parkingId=query.get("parkingId")||""; const slotId=query.get("slotId")||""; const initialStart=query.get("start")||""; const initialEnd=query.get("end")||"";
 const {data:parking}=useParkingDetail(parkingId); const vehicles=useVehicles(); const services=useParkingServices(parkingId); const create=useCreateBooking();
 const [vehicleId,setVehicleId]=useState(""); const [start,setStart]=useState(initialStart); const [end,setEnd]=useState(initialEnd); const [selected,setSelected]=useState<Record<string,number>>({}); const [error,setError]=useState(""); const careRequested=query.get("care")==="1";
 const vehicle=vehicles.data?.data.find(v=>String(v.id)===String(vehicleId)) || vehicles.data?.data.find(v=>v.vehicle_type === "CAR") || vehicles.data?.data.find(v=>v.vehicle_type === "EV") || vehicles.data?.data[0]; const effectiveVehicleId=vehicleId||vehicle?.id||""; const vehicleType=(vehicle?.vehicle_type||"CAR") as VehicleType; const slot=parking?.data?.slots.find(s=>String(s.id)===slotId); const hours=start&&end?Math.max(0,(new Date(end).getTime()-new Date(start).getTime())/3600000):0;
 useEffect(()=>{ if(!services.data?.data.length) return; setSelected(current=>Object.fromEntries(Object.entries(current).filter(([id,qty])=>qty>0 && services.data!.data.some(s=>String(s.id)===id && isVisibleForVehicle(s.name,vehicleType))))); },[services.data,vehicleType]);
 useEffect(()=>{if(!careRequested||!services.data?.data.length||Object.keys(selected).length)return;const preferred=vehicleType === "BIKE" ? /bike wash/i : vehicleType === "EV" ? /complete car clean|car cleaning/i : /car cleaning|complete car clean/i;const wanted=services.data.data.find(s=>preferred.test(s.name) && isVisibleForVehicle(s.name,vehicleType));if(wanted)setSelected({[wanted.id]:1})},[careRequested,services.data,vehicleType,selected]);
 const servicesTotal=useMemo(()=>services.data?.data.reduce((sum,s)=>sum+Number(s.price)*(selected[s.id]||0),0)||0,[services.data,selected]); const parkingTotal=slot?Number(slot.price_per_hour)*hours:0; const total=parkingTotal+servicesTotal;
 const submit=async()=>{setError("");if(!parkingId||!slotId||!start||!end){setError("Choose parking timing and slot first.");return}const s=new Date(start),e=new Date(end);if(e<=s){setError("End time must be after start time.");return}if(!effectiveVehicleId){setError("Add/select a vehicle before booking.");return}try{const result=await create.mutateAsync({slot_id:Number(slotId),vehicle_id:Number(effectiveVehicleId),start_time:s.toISOString(),end_time:e.toISOString(),services:Object.entries(selected).filter(([,q])=>q>0).map(([service_id,quantity])=>({service_id:Number(service_id),quantity}))});router.replace(`/bookings/${result.data.id}`)}catch(err){setError(getApiError(err).message)}};
 return <AppShell><main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><Link href={parkingId?`/parking/${parkingId}`:"/parking"} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="h-4 w-4"/>Back</Link><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_360px]"><Card className="p-5 sm:p-7"><div className="text-xs font-bold uppercase tracking-[.18em] text-cyan-600">RESERVATION</div><h1 className="mt-2 text-3xl font-bold">Reserve your spot + care.</h1><p className="mt-2 text-sm text-slate-500">{parking?.data?.name||"Parking"}{slot?` · ${slot.slot_code}`:""}</p>{error&&<div className="mt-4"><Alert message={error}/></div>}
 <div className="mt-6 grid gap-4 sm:grid-cols-2"><Input label="Start" type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/><Input label="End" type="datetime-local" min={start||undefined} value={end} onChange={e=>setEnd(e.target.value)}/></div>
 <label className="mt-5 block"><span className="text-sm font-semibold">Vehicle</span><select value={effectiveVehicleId} onChange={e=>setVehicleId(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">{vehicles.data?.data.map(v=><option key={v.id} value={v.id}>{v.plate_number} · {v.vehicle_type}</option>)}</select></label>{!vehicles.data?.data.length&&!vehicles.isLoading&&<Alert tone="info" message="No vehicle found. Add one from My account → Vehicles before booking."/>}
 <div className="mt-7 border-t border-slate-100 pt-6"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-cyan-600"/><h2 className="font-bold">Parkkar Care</h2></div><p className="mt-1 text-xs text-slate-500">Tick a cleaning option to reveal its price. Car is selected by default, but bikes and EVs are supported too.</p><div className="mt-4">{services.data?.data?<CareServicePicker services={services.data.data} vehicleType={vehicleType} selected={selected} onChange={setSelected}/>:<div className="h-24 animate-pulse rounded-2xl bg-slate-100"/>}</div></div><Button className="mt-7 w-full" loading={create.isPending} onClick={submit}>Create booking</Button><p className="mt-3 text-center text-xs text-slate-500">Payment continues on the booking page through Razorpay.</p></Card>
 <Card dark className="h-fit p-6"><div className="text-xs font-bold uppercase tracking-[.18em] text-slate-400">SUMMARY</div><h2 className="mt-2 text-xl font-bold">{parking?.data?.name||"Parking"}</h2><div className="mt-6 space-y-3 text-sm text-slate-300"><div className="flex justify-between"><span>Slot</span><b className="text-white">{slot?.slot_code||"—"}</b></div><div className="flex justify-between"><span>Duration</span><b className="text-white">{hours?`${hours.toFixed(1)} h`:"—"}</b></div><div className="flex justify-between"><span>Parking</span><b className="text-white">{money(String(parkingTotal))}</b></div><div className="flex justify-between"><span>Care</span><b className="text-white">{money(String(servicesTotal))}</b></div></div><div className="mt-6 border-t border-white/10 pt-5"><div className="flex items-end justify-between"><span className="text-slate-400">Estimated total</span><strong className="text-3xl">{money(String(total))}</strong></div><p className="mt-3 text-xs leading-5 text-slate-500"><Clock3 className="mr-1 inline h-3.5 w-3.5"/>Backend remains authoritative for the final booking total.</p></div></Card></div></main></AppShell>
}
