"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Bike, CarFront, Sparkles, Wrench } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { useServices } from "@/hooks/useResources";
import { CareServicePicker, isVisibleForVehicle } from "@/components/care/CareServicePicker";
import type { VehicleType } from "@/types/vehicle";
import { useLanguage } from "@/contexts/LanguageContext";

export default function CarePage(){
 const {t}=useLanguage(); const [vehicle,setVehicle]=useState<VehicleType>("CAR"); const [selected,setSelected]=useState<Record<string,number>>({}); const {data,isLoading}=useServices(); useEffect(()=>{if(!data?.data.length)return;setSelected(current=>Object.fromEntries(Object.entries(current).filter(([id,qty])=>qty>0 && data.data.some(s=>String(s.id)===id && isVisibleForVehicle(s.name,vehicle)))));},[data,vehicle]);
 return <AppShell><main className="bg-slate-50"><section className="bg-slate-950 px-4 py-14 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><div className="max-w-3xl"><div className="text-xs font-bold uppercase tracking-[.22em] text-cyan-400">PARKKAR CARE</div><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">{t.careTitle}</h1><p className="mt-4 text-base leading-7 text-slate-400">{t.careBody}</p></div></div></section><section className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><div className="grid gap-7 lg:grid-cols-[1fr_340px]"><div><div className="grid grid-cols-4 gap-2">{[["CAR",CarFront,t.car],["BIKE",Bike,t.bike],["EV",CarFront,t.ev],["OTHER",Wrench,t.other]].map(([id,Icon,label])=>{const I=Icon as typeof CarFront;return <button key={id as string} type="button" onClick={()=>setVehicle(id as VehicleType)} className={`rounded-2xl border p-3 text-sm font-semibold ${vehicle===id?"border-cyan-400 bg-cyan-50 text-cyan-700":"border-slate-200 bg-white text-slate-600"}`}><I className="mx-auto h-5 w-5"/><span className="mt-2 block">{label as string}</span></button>})}</div><div className="mt-5 rounded-3xl border border-slate-200 bg-white p-5 sm:p-7"><div className="flex items-center gap-3"><span className="rounded-2xl bg-cyan-100 p-3 text-cyan-700"><Sparkles/></span><div><h2 className="text-xl font-bold">Cleaning + roadside help</h2><p className="text-sm text-slate-500">Select a service to see exactly what is included and its price.</p></div></div><div className="mt-6">{isLoading?<div className="h-40 animate-pulse rounded-2xl bg-slate-100"/>:<CareServicePicker services={data?.data||[]} vehicleType={vehicle} selected={selected} onChange={setSelected}/>}</div></div></div><aside className="h-fit rounded-3xl bg-slate-950 p-6 text-white lg:sticky lg:top-24"><div className="text-xs font-bold uppercase tracking-[.18em] text-cyan-400">NEXT STEP</div><h2 className="mt-2 text-2xl font-bold">Attach care to parking</h2><p className="mt-3 text-sm leading-6 text-slate-400">Care is designed to be selected during a real parking booking so the service can be scheduled while your vehicle is parked.</p><div className="mt-6 rounded-2xl bg-white/5 p-4"><p className="text-xs text-slate-500">Selected services</p><p className="mt-2 font-bold">{Object.values(selected).reduce((a,b)=>a+b,0)} service(s)</p></div><Link href="/parking" className="mt-4 flex items-center justify-center gap-2 rounded-2xl bg-cyan-400 px-4 py-3 font-bold text-slate-950">Find parking <ArrowRight className="h-4 w-4"/></Link><div className="mt-5 flex items-start gap-2 text-xs leading-5 text-slate-500"><Wrench className="mt-0.5 h-4 w-4 shrink-0"/>Puncture assistance is intended for eligible tubeless tyres. Parts/replacement are quoted separately if needed.</div></aside></div></section></main></AppShell>
}
