"use client";
import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { CarFront, Filter, MapPin, Search, Sparkles } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { ParkingCard } from "@/components/parking/ParkingCard";
import { ParkingDiscoveryMap } from "@/components/parking/ParkingDiscoveryMap";
import { Skeleton } from "@/components/ui/Skeleton";
import { FallbackImage } from "@/components/ui/FallbackImage";
import { useParking, useParkingRecommendations } from "@/hooks/useResources";
import { CITY_COORDS, INDIAN_CAPITALS, MALLS } from "@/data/parkkarData";

export default function ParkingPage(){
 const router=useRouter(); const params=useSearchParams(); const [city,setCity]=useState(params.get("city")||""); const [type,setType]=useState(""); const [max,setMax]=useState(""); const [loc,setLoc]=useState<{lat:number;lng:number}|null>(null);
 useEffect(()=>{if(navigator.geolocation) navigator.geolocation.getCurrentPosition(p=>setLoc({lat:p.coords.latitude,lng:p.coords.longitude}),()=>{});},[]);
 const {data,isLoading,isError}=useParking({city:city||undefined,propertyType:type||undefined,maxPrice:max?Number(max):undefined,limit:12});
 const {data:recommendations}=useParkingRecommendations({lat:loc?.lat||CITY_COORDS[city]?.lat||CITY_COORDS.Kanpur.lat,lng:loc?.lng||CITY_COORDS[city]?.lng||CITY_COORDS.Kanpur.lng,radius_km:25,limit:5},true);
 const locations=data?.data||[]; const center=CITY_COORDS[city]||CITY_COORDS.Kanpur;
 return <AppShell><main className="bg-slate-50"><section className="bg-slate-950 px-4 py-12 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><div className="text-xs font-bold uppercase tracking-[.22em] text-cyan-400">PARKING DISCOVERY</div><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Find a parking space that actually fits your stop.</h1><p className="mt-4 text-slate-400">Filter by city, property and price. Open a location to see its building-aware slot map.</p></div><div className="mt-7 grid gap-3 lg:grid-cols-[1.3fr_.8fr_.6fr_auto]"><input list="city-list" value={city} onChange={e=>setCity(e.target.value)} placeholder="Search city" className="h-12 rounded-2xl bg-white px-4 text-sm text-slate-950 outline-none"/><select value={type} onChange={e=>setType(e.target.value)} className="h-12 rounded-2xl bg-white px-4 text-sm text-slate-950"><option value="">All property types</option><option value="MALL">Mall</option><option value="HOTEL">Hotel</option><option value="COMMERCIAL_BUILDING">Commercial building</option><option value="BANQUET_HALL">Banquet hall</option></select><input type="number" min="0" value={max} onChange={e=>setMax(e.target.value)} placeholder="Max ₹ / hour" className="h-12 rounded-2xl bg-white px-4 text-sm text-slate-950 outline-none"/><button type="button" onClick={()=>router.refresh()} className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl bg-cyan-400 px-5 font-bold text-slate-950"><Search className="h-4 w-4"/>Search</button></div><datalist id="city-list">{INDIAN_CAPITALS.map(c=><option key={c} value={c}/>)}<option value="Kanpur"/></datalist></div></section>
 <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="grid gap-7 xl:grid-cols-[1fr_430px]"><div><div className="mb-5 flex items-center justify-between"><div><p className="text-sm text-slate-500">{locations.length} locations in {city||"your search area"}</p><h2 className="mt-1 text-2xl font-bold">Available parking</h2></div><span className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-2 text-xs font-semibold text-slate-600 shadow-sm"><Filter className="h-3.5 w-3.5"/>Filters live</span></div>{isLoading?<div className="grid gap-5 md:grid-cols-2">{Array.from({length:4}).map((_,i)=><Skeleton key={i} className="h-[360px] rounded-3xl"/>)}</div>:isError?<div className="rounded-3xl border border-red-200 bg-white p-8 text-red-700">Parking data could not be loaded. Check that the backend is running.</div>:locations.length?<div className="grid gap-5 md:grid-cols-2">{locations.map(s=><ParkingCard key={s.id} spot={s}/>)}</div>:<div className="rounded-3xl border border-slate-200 bg-white p-10 text-center"><CarFront className="mx-auto h-8 w-8 text-slate-400"/><h3 className="mt-4 font-bold">No parking matches these filters.</h3><p className="mt-1 text-sm text-slate-500">Try another city or remove the price/property filter.</p></div>}</div><aside className="xl:sticky xl:top-24 xl:h-[calc(100vh-7rem)]"><div className="h-full rounded-3xl bg-white p-3 shadow-sm"><div className="flex items-center justify-between px-3 py-2"><div><p className="font-bold">Live parking map</p><p className="text-xs text-slate-500">Tap a marker to open its building</p></div><MapPin className="h-5 w-5 text-cyan-600"/></div><div className="h-[520px]"><ParkingDiscoveryMap locations={locations} center={center} onSelect={id=>router.push(`/parking/${id}`)}/></div></div></aside></div></section>
 <section className="border-t border-slate-200 bg-white px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-cyan-600">MALL DIRECTORY</div><h2 className="mt-2 text-3xl font-bold">Kanpur + Lucknow locations, building by building.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Verified public information is shown here. A detailed floor map is displayed only where the parking layout is supported; otherwise Parkkar says it is unavailable instead of inventing one.</p></div><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{MALLS.map(m=> <article key={m.id} className="overflow-hidden rounded-3xl border border-slate-200 bg-slate-50"><div className="h-40 bg-slate-200"><FallbackImage src={m.imageUrl} alt={`${m.name} exterior`} className="h-full w-full object-cover" fallback={<div className="flex h-full items-center justify-center bg-[radial-gradient(circle_at_30%_30%,rgba(34,211,238,.25),transparent_35%),linear-gradient(135deg,#0f172a,#172554)] p-6 text-center text-sm font-bold text-white">{m.name}</div>}/></div><div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="font-bold">{m.name}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${m.mapAvailable?"bg-emerald-50 text-emerald-700":"bg-slate-200 text-slate-600"}`}>{m.mapAvailable?"MAP AVAILABLE":"MAP UNAVAILABLE"}</span></div><p className="mt-2 text-xs text-slate-500">{m.address}</p><p className="mt-3 text-xs leading-5 text-slate-600">{m.mapNote}</p><button type="button" onClick={()=>{setCity(m.city);window.scrollTo({top:0,behavior:"smooth"})}} className="mt-4 rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-bold text-white">Search {m.city} parking</button></div></article>)}</div></div></section>

 {recommendations?.data?.length ? <section className="border-t border-slate-200 bg-white px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-cyan-600"><Sparkles className="h-4 w-4"/>Smart suggestions</div><h2 className="mt-2 text-3xl font-bold">Nearby options based on distance and availability.</h2><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{recommendations.data.slice(0,3).map((r:any)=><button key={r.id} onClick={()=>router.push(`/parking/${r.id}`)} className="rounded-3xl border border-slate-200 bg-slate-50 p-5 text-left hover:border-cyan-300"><div className="text-sm font-bold">{r.name}</div><div className="mt-1 text-xs text-slate-500">{r.distance_km?.toFixed?.(1)??r.distance_km} km · {r.available_slots} slots available</div><div className="mt-4 text-sm font-semibold text-cyan-700">View building →</div></button>)}</div></div></section>:null}
 </main></AppShell>
}
